# Generated by Django 4.1.3 on 2022-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('pts', models.CharField(max_length=60)),
                ('gd', models.CharField(max_length=60)),
                ('mp', models.CharField(max_length=60)),
            ],
        ),
    ]
